version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 1
    groups:
      npm-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
